### ISSUE TITLE
Sync not working with React Table Grid component

### ISSUE THREAD

**Issue by deepak2431** [okonet/react-scroll-sync#63] opened 2021-09-06 17:55 UTC
I am trying to use Sync for two tables created with https://devexpress.github.io/devextreme-reactive/docs/ but the sync doesn't works.
My code: 
https://gist.github.com/deepak2431/ac8a33dec99f685a2c64f887b00df7b2
Thanks in advance!

**Comment by deepak2431** [comment] 2021-09-06 17:55
@okonet Please have a look!

**Comment by okonet** [comment] 2021-09-15 09:59
Sorry but I can't offering support / consulting services for free. I would suggest posting a question on StackOverflow or creating a discussion here.

If you believe it's an issue with the library, please provide a reproducible case (CodeSanbox link or a repo) and describe the issue so it's easy to understand what the problem is. Until that I'm considering it's not an issue and will close it. Thanks!

**Closed by okonet** 2021-09-15 09:59 UTC
